### ISSUE TITLE
Very small tea-cup dataset

### ISSUE THREAD

**Issue by markcmiller86** [visit-dav/largedata#3]
This is a very small "brick of values" dataset stored as a VisIt *image volume* data format. BOV would have been better.

Its from a CT scan of a ceramic tea cup with a *plastic* spoon in the cup and was scanned in the late 1980's.

It is 102 *slices* and I think each slice (though you can confirm for sure by just opening and plotting in VisIt) is 128x128

[tcup_imgvol.tar.gz](https://github.com/visit-dav/largedata/files/7715579/tcup_imgvol.tar.gz)

**Comment by markcmiller86** [comment]
@griffin28 you can get the tea cup dataset I mentioned here. Sorry if its clumsily formatted. I thought I had it in Silo format but can't find that one.

**Comment by markcmiller86** [comment]
@ARSanderson if you can gzip your dataset down to < 25Mbs, you can attach it to a [new issue](https://github.com/visit-dav/largedata/issues/new/choose) here.

**Comment by griffin28** [comment]
Got it @markcmiller86. Thanks!

**Comment by markcmiller86** [comment]
@griffin28 it looks like there is indeed some BOV data too if that is better. You can find it in our [bov_test_data.7z](https://github.com/visit-dav/visit/blob/develop/data/bov_test_data.7z) archive with `tcup.bov` (meta file) and `tcup.bytes` (raw data file 0...255 value data).
